[theme]
base="dark"
primaryColor="#f5c518"
backgroundColor="#1f1f1f"
secondaryBackgroundColor="#272727"

[theme]
base="dark"
primaryColor="#f5c518"
backgroundColor="#1f1f1f"
secondaryBackgroundColor="#272727"
font="serif"

[theme]
base="dark"
primaryColor="#f5c518"
backgroundColor="#1f1f1f"
secondaryBackgroundColor="#272727"
font="monospace"
